const HOY = new Date();
const dias = (n) => new Date(HOY.getTime() - n * 86400000).toISOString();

export const DEMO_ELEAM = {
  nombre: "Residencia Los Arrayanes",
  plan: "Estándar",
  ciudad: "Santiago",
};

export const DEMO_RESIDENTES = [
  {
    id: "res-001",
    nombre: "María Elena",
    apellido: "Soto Quiroga",
    rut: "6.543.210-K",
    fecha_nacimiento: "1938-04-12",
    sexo: "femenino",
    estado_civil: "viuda",
    diagnostico_principal: "Alzheimer moderado, HTA controlada",
    alergias: ["Penicilina"],
    indice_barthel: 35,
    nivel_dependencia: "severo",
    fecha_ingreso: "2022-08-15",
    estado: "activo",
    habitacion: "A-101",
    cama: "1",
  },
  {
    id: "res-002",
    nombre: "Carlos Arturo",
    apellido: "Fuentes Morales",
    rut: "5.234.567-3",
    fecha_nacimiento: "1942-11-28",
    sexo: "masculino",
    estado_civil: "casado",
    diagnostico_principal: "Parkinson estadio III, DM tipo 2",
    alergias: [],
    indice_barthel: 55,
    nivel_dependencia: "moderado",
    fecha_ingreso: "2023-02-10",
    estado: "activo",
    habitacion: "A-102",
    cama: "1",
  },
  {
    id: "res-003",
    nombre: "Rosa Amelia",
    apellido: "Vargas Pineda",
    rut: "8.901.234-5",
    fecha_nacimiento: "1935-07-03",
    sexo: "femenino",
    estado_civil: "soltera",
    diagnostico_principal: "Insuficiencia cardíaca compensada, artrosis severa",
    alergias: ["AINEs"],
    indice_barthel: 20,
    nivel_dependencia: "total",
    fecha_ingreso: "2021-11-22",
    estado: "activo",
    habitacion: "B-201",
    cama: "2",
  },
  {
    id: "res-004",
    nombre: "Héctor Gonzalo",
    apellido: "Riquelme Aravena",
    rut: "7.654.321-9",
    fecha_nacimiento: "1945-02-14",
    sexo: "masculino",
    estado_civil: "divorciado",
    diagnostico_principal: "ACV con secuelas motoras, disfagia moderada",
    alergias: ["Sulfonamidas"],
    indice_barthel: 45,
    nivel_dependencia: "moderado",
    fecha_ingreso: "2023-06-05",
    estado: "activo",
    habitacion: "B-202",
    cama: "1",
  },
  {
    id: "res-005",
    nombre: "Luisa Carmen",
    apellido: "Espinoza Toro",
    rut: "9.012.345-6",
    fecha_nacimiento: "1950-09-19",
    sexo: "femenino",
    estado_civil: "casada",
    diagnostico_principal: "Depresión mayor tratada, hipotiroidismo",
    alergias: [],
    indice_barthel: 75,
    nivel_dependencia: "leve",
    fecha_ingreso: "2024-01-08",
    estado: "activo",
    habitacion: "C-301",
    cama: "1",
  },
];

export const DEMO_SIGNOS = [
  {
    id: "sv-001",
    residente_id: "res-001",
    residente_nombre: "María Elena Soto",
    fecha_hora: dias(0) + "T08:30:00.000Z",
    turno: "mañana",
    presion_sistolica: 142,
    presion_diastolica: 88,
    frecuencia_cardiaca: 78,
    frecuencia_respiratoria: 18,
    temperatura: 36.8,
    saturacion_oxigeno: 96,
    glucosa: 118,
    dolor_escala: 2,
    estado_conciencia: "alerta",
  },
  {
    id: "sv-002",
    residente_id: "res-002",
    residente_nombre: "Carlos Arturo Fuentes",
    fecha_hora: dias(0) + "T09:00:00.000Z",
    turno: "mañana",
    presion_sistolica: 128,
    presion_diastolica: 80,
    frecuencia_cardiaca: 72,
    frecuencia_respiratoria: 16,
    temperatura: 36.5,
    saturacion_oxigeno: 97,
    glucosa: 186,
    dolor_escala: 4,
    estado_conciencia: "alerta",
  },
  {
    id: "sv-003",
    residente_id: "res-003",
    residente_nombre: "Rosa Amelia Vargas",
    fecha_hora: dias(0) + "T08:45:00.000Z",
    turno: "mañana",
    presion_sistolica: 155,
    presion_diastolica: 95,
    frecuencia_cardiaca: 92,
    frecuencia_respiratoria: 22,
    temperatura: 37.2,
    saturacion_oxigeno: 91,
    glucosa: null,
    dolor_escala: 6,
    estado_conciencia: "alerta",
  },
  {
    id: "sv-004",
    residente_id: "res-001",
    residente_nombre: "María Elena Soto",
    fecha_hora: dias(1) + "T08:30:00.000Z",
    turno: "mañana",
    presion_sistolica: 138,
    presion_diastolica: 85,
    frecuencia_cardiaca: 76,
    frecuencia_respiratoria: 17,
    temperatura: 36.6,
    saturacion_oxigeno: 97,
    glucosa: 112,
    dolor_escala: 1,
    estado_conciencia: "alerta",
  },
  {
    id: "sv-005",
    residente_id: "res-004",
    residente_nombre: "Héctor Gonzalo Riquelme",
    fecha_hora: dias(0) + "T09:15:00.000Z",
    turno: "mañana",
    presion_sistolica: 132,
    presion_diastolica: 82,
    frecuencia_cardiaca: 68,
    frecuencia_respiratoria: 15,
    temperatura: 36.4,
    saturacion_oxigeno: 98,
    glucosa: 104,
    dolor_escala: 3,
    estado_conciencia: "alerta",
  },
];

export const DEMO_OBSERVACIONES = [
  {
    id: "obs-001",
    residente_id: "res-001",
    residente_nombre: "María Elena Soto",
    turno: "mañana",
    tipo: "comportamiento",
    descripcion: "Residente agitada al despertar. Desorientada en tiempo y espacio. Se la orientó con fotografías familiares, logrando calmarla.",
    acciones_tomadas: "Se informó a médico tratante. Se reforzó rutina de orientación.",
    requiere_seguimiento: true,
    creado_en: dias(0) + "T08:45:00.000Z",
    autor: "Enf. Paola Díaz",
  },
  {
    id: "obs-002",
    residente_id: "res-002",
    residente_nombre: "Carlos Arturo Fuentes",
    turno: "tarde",
    tipo: "alimentacion",
    descripcion: "Buena ingesta almuerzo (100%). Acepta dieta hipocalórica sin resistencia. Control glucemia post-prandial: 186 mg/dL.",
    acciones_tomadas: "Ajuste de insulina según protocolo. Nota a nutricionista.",
    requiere_seguimiento: false,
    creado_en: dias(0) + "T14:30:00.000Z",
    autor: "TENS Roberto Salinas",
  },
  {
    id: "obs-003",
    residente_id: "res-003",
    residente_nombre: "Rosa Amelia Vargas",
    turno: "mañana",
    tipo: "clinica",
    descripcion: "Disnea leve al movimiento. Saturación 91% en reposo. Edema en miembros inferiores ++.",
    acciones_tomadas: "Oxígeno suplementario 2L/min. Médico evaluó, ajustó diurético. Reposo indicado.",
    requiere_seguimiento: true,
    creado_en: dias(0) + "T09:00:00.000Z",
    autor: "Enf. Paola Díaz",
  },
  {
    id: "obs-004",
    residente_id: "res-005",
    residente_nombre: "Luisa Carmen Espinoza",
    turno: "tarde",
    tipo: "bienestar",
    descripcion: "Participó activamente en taller de tejido. Estado anímico excelente. Comentó que extraña a su hijo pero está contenta con las actividades.",
    acciones_tomadas: null,
    requiere_seguimiento: false,
    creado_en: dias(0) + "T16:00:00.000Z",
    autor: "Terapeuta Claudia Muñoz",
  },
  {
    id: "obs-005",
    residente_id: "res-004",
    residente_nombre: "Héctor Gonzalo Riquelme",
    turno: "mañana",
    tipo: "rehabilitacion",
    descripcion: "Sesión kinesiología: 20 min ejercicios motores finos mano derecha. Avance leve en agarre de objetos pequeños.",
    acciones_tomadas: "Se continuará con protocolo de rehabilitación diaria.",
    requiere_seguimiento: false,
    creado_en: dias(0) + "T10:30:00.000Z",
    autor: "Kinesiólogo Marcos Pinto",
  },
];

export const DEMO_VISITAS = [
  {
    id: "vis-001",
    residente_id: "res-001",
    familiar_nombre: "Pedro Soto (hijo)",
    fecha_hora: dias(3) + "T15:00:00.000Z",
    duracion_min: 90,
    notas: "Trajo flores y fotos de los nietos. Residente muy contenta.",
  },
  {
    id: "vis-002",
    residente_id: "res-001",
    familiar_nombre: "Ana Soto (hija)",
    fecha_hora: dias(10) + "T11:00:00.000Z",
    duracion_min: 60,
    notas: null,
  },
  {
    id: "vis-003",
    residente_id: "res-001",
    familiar_nombre: "Pedro Soto (hijo)",
    fecha_hora: dias(17) + "T16:30:00.000Z",
    duracion_min: 45,
    notas: "Trajo torta de cumpleaños anticipada.",
  },
];

export const DEMO_ACRED_AMBITOS = [
  { codigo: "A01", nombre: "Habilitación", total: 5, cumple: 4, pendiente: 1 },
  { codigo: "A02", nombre: "Infraestructura", total: 5, cumple: 3, pendiente: 2 },
  { codigo: "A03", nombre: "Instalaciones", total: 7, cumple: 5, pendiente: 1, vencido: 1 },
  { codigo: "A04", nombre: "Seguridad y Emergencia", total: 6, cumple: 6, pendiente: 0 },
  { codigo: "A05", nombre: "Dirección Técnica", total: 4, cumple: 4, pendiente: 0 },
  { codigo: "A06", nombre: "Recursos Humanos", total: 7, cumple: 5, pendiente: 2 },
  { codigo: "A07", nombre: "Prevención y Control de Infecciones", total: 7, cumple: 7, pendiente: 0 },
  { codigo: "A08", nombre: "Atención al Residente", total: 7, cumple: 4, pendiente: 3 },
  { codigo: "A09", nombre: "Derechos del Residente", total: 4, cumple: 4, pendiente: 0 },
  { codigo: "A10", nombre: "Medicamentos", total: 5, cumple: 3, pendiente: 2 },
  { codigo: "A11", nombre: "Alimentación", total: 5, cumple: 5, pendiente: 0 },
  { codigo: "A12", nombre: "Aseo y Sanitización", total: 5, cumple: 4, pendiente: 1 },
  { codigo: "A13", nombre: "Participación Familiar", total: 5, cumple: 3, pendiente: 2 },
  { codigo: "A14", nombre: "Fiscalización", total: 4, cumple: 2, pendiente: 2 },
];

export const DEMO_ACRED_KPI = {
  totalRequisitos: 76,
  cumple: 63,
  pendiente: 11,
  vencido: 1,
  observado: 1,
  pct: Math.round((63 / 76) * 100),
};

export const DEMO_RESIDENTE_FAMILIAR = DEMO_RESIDENTES[0];
