export const MOCK_RESIDENTS = [
  {
    id: "mock-1",
    nombre: "Carmen",
    apellido: "González",
    rut: "8.765.432-1",
    fecha_nacimiento: "1942-03-15",
    sexo: "femenino",
    estado: "activo",
    habitacion: "101",
    cama: "A",
    diagnostico_principal: "Hipertensión arterial, Diabetes tipo 2",
    nivel_dependencia: "moderado",
    indice_barthel: 55,
    fecha_ingreso: "2023-05-12",
    prevision: "FONASA A",
    nombre_contacto: "Claudia González",
    telefono_contacto: "+56 9 8765 4321",
    parentesco_contacto: "Hija",
  },
  {
    id: "mock-2",
    nombre: "Roberto",
    apellido: "Muñoz",
    rut: "7.654.321-K",
    fecha_nacimiento: "1938-11-22",
    sexo: "masculino",
    estado: "activo",
    habitacion: "102",
    cama: "B",
    diagnostico_principal: "Artrosis severa, Deterioro cognitivo leve",
    nivel_dependencia: "severo",
    indice_barthel: 30,
    fecha_ingreso: "2022-08-30",
    prevision: "FONASA B",
    nombre_contacto: "Jorge Muñoz",
    telefono_contacto: "+56 9 7654 3210",
    parentesco_contacto: "Hijo",
  },
  {
    id: "mock-3",
    nombre: "Elena",
    apellido: "Vásquez",
    rut: "6.543.210-5",
    fecha_nacimiento: "1940-07-08",
    sexo: "femenino",
    estado: "hospitalizado",
    habitacion: "103",
    cama: "A",
    diagnostico_principal: "Fractura de cadera, Anemia ferropénica",
    nivel_dependencia: "total",
    indice_barthel: 10,
    fecha_ingreso: "2024-01-20",
    prevision: "FONASA A",
    nombre_contacto: "Pedro Vásquez",
    telefono_contacto: "+56 9 6543 2100",
    parentesco_contacto: "Sobrino",
  },
  {
    id: "mock-4",
    nombre: "Teresa",
    apellido: "Rojas",
    rut: "9.112.445-6",
    fecha_nacimiento: "1935-02-03",
    sexo: "femenino",
    estado: "activo",
    habitacion: "104",
    cama: "A",
    diagnostico_principal: "EPOC, insuficiencia cardiaca compensada",
    nivel_dependencia: "total",
    indice_barthel: 15,
    fecha_ingreso: "2021-10-05",
    prevision: "FONASA A",
    nombre_contacto: "Marcela Rojas",
    telefono_contacto: "+56 9 3344 5566",
    parentesco_contacto: "Nieta",
  },
  {
    id: "mock-5",
    nombre: "Luis",
    apellido: "Araya",
    rut: "10.223.445-0",
    fecha_nacimiento: "1946-09-18",
    sexo: "masculino",
    estado: "activo",
    habitacion: "105",
    cama: "B",
    diagnostico_principal: "Parkinson, hipertensión arterial",
    nivel_dependencia: "moderado",
    indice_barthel: 45,
    fecha_ingreso: "2024-03-11",
    prevision: "FONASA B",
    nombre_contacto: "Paula Araya",
    telefono_contacto: "+56 9 7788 9900",
    parentesco_contacto: "Hija",
  },
];

export const MOCK_VITAL_SIGNS = [
  {
    id: "vs-1",
    residente_id: "mock-1",
    residente_nombre: "Carmen González",
    fecha_hora: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    turno: "mañana",
    presion_sistolica: 130,
    presion_diastolica: 80,
    frecuencia_cardiaca: 72,
    frecuencia_respiratoria: 17,
    temperatura: 36.5,
    saturacion_oxigeno: 97,
    glucosa: 118,
    dolor_escala: 2,
    estado_conciencia: "alerta",
  },
  {
    id: "vs-2",
    residente_id: "mock-2",
    residente_nombre: "Roberto Muñoz",
    fecha_hora: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    turno: "mañana",
    presion_sistolica: 145,
    presion_diastolica: 90,
    frecuencia_cardiaca: 68,
    frecuencia_respiratoria: 18,
    temperatura: 36.8,
    saturacion_oxigeno: 94,
    glucosa: 132,
    dolor_escala: 5,
    estado_conciencia: "alerta",
  },
  {
    id: "vs-4",
    residente_id: "mock-4",
    residente_nombre: "Teresa Rojas",
    fecha_hora: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    turno: "mañana",
    presion_sistolica: 92,
    presion_diastolica: 58,
    frecuencia_cardiaca: 112,
    frecuencia_respiratoria: 28,
    temperatura: 37.9,
    saturacion_oxigeno: 88,
    glucosa: 104,
    dolor_escala: 6,
    estado_conciencia: "somnoliento",
  },
  {
    id: "vs-5",
    residente_id: "mock-5",
    residente_nombre: "Luis Araya",
    fecha_hora: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    turno: "noche",
    presion_sistolica: 125,
    presion_diastolica: 76,
    frecuencia_cardiaca: 78,
    frecuencia_respiratoria: 16,
    temperatura: 36.4,
    saturacion_oxigeno: 96,
    glucosa: 98,
    dolor_escala: 1,
    estado_conciencia: "alerta",
  },
  {
    id: "vs-3",
    residente_id: "mock-1",
    residente_nombre: "Carmen González",
    fecha_hora: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    turno: "tarde",
    presion_sistolica: 128,
    presion_diastolica: 78,
    frecuencia_cardiaca: 74,
    frecuencia_respiratoria: 16,
    temperatura: 36.3,
    saturacion_oxigeno: 98,
    glucosa: 110,
    dolor_escala: 1,
    estado_conciencia: "alerta",
  },
];

export const MOCK_OBSERVATIONS = [
  {
    id: "obs-1",
    residente_id: "mock-2",
    residente_nombre: "Roberto Muñoz",
    fecha_hora: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    turno: "mañana",
    tipo: "cambio_posicion",
    descripcion: "Se realizó cambio de posición cada 2 horas para prevención de escaras. Sin lesiones cutáneas observadas.",
    acciones_tomadas: "Cambio decúbito lateral derecho, hidratación de piel con crema.",
    requiere_seguimiento: false,
  },
  {
    id: "obs-2",
    residente_id: "mock-1",
    residente_nombre: "Carmen González",
    fecha_hora: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    turno: "mañana",
    tipo: "administracion_medicamento",
    descripcion: "Administración de Metformina 850mg y Enalapril 5mg según pauta médica. Residente en buen estado general.",
    acciones_tomadas: "Medicamentos administrados. Se verificó deglución.",
    requiere_seguimiento: false,
  },
  {
    id: "obs-3",
    residente_id: "mock-3",
    residente_nombre: "Elena Vásquez",
    fecha_hora: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    turno: "mañana",
    tipo: "visita_medica",
    descripcion: "Visita médica de seguimiento post fractura de cadera. Se evaluó estado de cicatrización y movilidad.",
    acciones_tomadas: "Médico indica continuar con rehabilitación. Nueva indicación: Calcio + Vitamina D.",
    requiere_seguimiento: true,
  },
  {
    id: "obs-4",
    residente_id: "mock-4",
    residente_nombre: "Teresa Rojas",
    fecha_hora: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    turno: "mañana",
    tipo: "incidente",
    descripcion: "Residente presenta disnea leve y baja saturación al control matinal.",
    acciones_tomadas: "Se eleva cabecera, se avisa a enfermería y se programa nuevo control en 30 minutos.",
    requiere_seguimiento: true,
  },
];
