const PRIVATE_ROUTE_TITLES = [
  [/^\/dashboard\/?$/, "Inicio"],
  [/^\/establecimiento\/?$/, "Establecimiento"],
  [/^\/personal\/equipo\/?$/, "Equipo"],
  [/^\/personal\/dotacion\/?$/, "Dotación"],
  [/^\/personal\/?$/, "Personal"],
  [/^\/cumplimiento\/requisito\/[^/]+\/?$/, "Requisito de cumplimiento"],
  [/^\/cumplimiento\/observaciones\/?$/, "Observaciones de cumplimiento"],
  [/^\/cumplimiento\/reporte\/?$/, "Reporte de cumplimiento"],
  [/^\/cumplimiento\/protocolos\/?$/, "Protocolos"],
  [/^\/cumplimiento\/emergencias\/?$/, "Emergencias"],
  [/^\/cumplimiento\/reclamos\/?$/, "Reclamos"],
  [/^\/cumplimiento\/?$/, "Cumplimiento"],
  [/^\/operacion\/turnos\/nuevo\/?$/, "Nueva entrega de turno"],
  [/^\/operacion\/turnos\/[^/]+\/?$/, "Entrega de turno"],
  [/^\/operacion\/turnos\/?$/, "Turnos"],
  [/^\/operacion\/cuidados\/?$/, "Tareas del turno"],
  [/^\/operacion\/medicamentos\/?$/, "Medicamentos"],
  [/^\/residents\/new\/?$/, "Nuevo residente"],
  [/^\/residents\/[^/]+\/edit\/?$/, "Editar residente"],
  [/^\/residents\/[^/]+\/?$/, "Ficha del residente"],
  [/^\/residents\/?$/, "Residentes"],
  [/^\/cobranza\/?$/, "Cobranza de residentes"],
  [/^\/vital-signs\/new\/?$/, "Registrar signos vitales"],
  [/^\/vital-signs\/?$/, "Signos vitales"],
  [/^\/observations\/new\/?$/, "Nueva observación"],
  [/^\/observations\/?$/, "Observaciones"],
  [/^\/eventos-adversos\/nuevo\/?$/, "Nuevo evento adverso"],
  [/^\/eventos-adversos\/[^/]+\/edit\/?$/, "Editar evento adverso"],
  [/^\/eventos-adversos\/[^/]+\/?$/, "Detalle del evento adverso"],
  [/^\/eventos-adversos\/?$/, "Eventos adversos"],
  [/^\/superadmin\/clientes\/?$/, "Uso por ELEAM"],
  [/^\/superadmin\/leads\/?$/, "Oportunidades comerciales"],
  [/^\/superadmin\/pagos\/?$/, "Pagos de la plataforma"],
  [/^\/superadmin\/tareas\/?$/, "Tareas comerciales"],
  [/^\/superadmin\/blog\/new\/?$/, "Nuevo artículo"],
  [/^\/superadmin\/blog\/[^/]+\/edit\/?$/, "Editar artículo"],
  [/^\/superadmin\/blog\/?$/, "Blog"],
  [/^\/superadmin\/?$/, "Administración de FichaEleam"],
  [/^\/cambiar-clave\/?$/, "Cambiar contraseña"],
  [/^\/sin-permisos\/?$/, "Acceso pendiente"],
];

export function getPrivateRouteTitle(pathname) {
  return PRIVATE_ROUTE_TITLES.find(([pattern]) => pattern.test(pathname))?.[1] ?? "FichaEleam";
}

