export const ACTIVATION_STORAGE_PREFIX = "fichaeleam_activation_v1_";

export const ACTIVATION_PLAYBOOKS = {
  admin_eleam: {
    id: "admin_first_occupied_bed",
    role: "admin_eleam",
    color: "teal",
    icon: "beds",
    mission: "Primera cama ocupada",
    introTitle: "Activa la operación base",
    introGreeting: "Hola, {nombre}. Partamos por lo indispensable.",
    introBody:
      "Crea una cama, registra un residente y deja la primera asignación lista.",
    introSupport:
      "La guía queda disponible sin interrumpir tu trabajo.",
    introCta: "Comenzar guía",
    introSkip: "Cerrar por ahora",
    activeLabel: "Guía activa",
    completedBadge: "Operación iniciada",
    completionTitle: "Listo: ya tienes una primera cama operativa.",
    completionBody:
      "Desde aquí puedes controlar ocupación, disponibilidad y traslados.",
    completionCta: "Ver ocupación",
    completionRoute: "/camas",
    secondaryCta: "Invitar equipo",
    secondaryRoute: "/equipo",
    afterComplete: [
      "Invita a tu equipo cuando tengas el flujo base listo.",
      "Registra signos vitales desde la ficha del residente.",
      "Prepara la carpeta SEREMI con documentos clave.",
    ],
    steps: [
      {
        id: "room_bed_ready",
        title: "Crea una habitación y una cama",
        body: "Empieza con una ubicación simple. Una habitación y una cama bastan.",
        help:
          "Usa códigos simples como Hab. 101 y Cama A. Después podrás ordenar o editar.",
        cta: "Crear cama",
        route: "/camas",
        matchRoutes: ["/camas"],
        icon: "beds",
        requiredFeature: "beds",
        requiredPermission: "asignar_camas",
        completionRule: "hasBedInventory",
      },
      {
        id: "resident_ready",
        title: "Registra un residente",
        body: "Crea la ficha con los datos mínimos. Puedes completar detalles después.",
        help: "La cama no se escribe aquí; se asigna desde Camas.",
        cta: "Registrar residente",
        route: "/residents/new",
        matchRoutes: ["/residents"],
        icon: "residents",
        requiredFeature: "residents",
        requiredPermission: "crear_residentes",
        completionRule: "hasActiveResident",
      },
      {
        id: "bed_assigned",
        title: "Asigna el residente a la cama",
        body: "Une la ficha con una cama disponible y deja la ocupación visible.",
        help:
          "Una cama ocupada queda bloqueada para evitar doble asignación.",
        cta: "Asignar cama",
        route: "/camas",
        matchRoutes: ["/camas"],
        icon: "beds",
        requiredFeature: "beds",
        requiredPermission: "asignar_camas",
        completionRule: "hasActiveBedAssignment",
      },
    ],
  },

  funcionario: {
    id: "staff_first_shift_action",
    role: "funcionario",
    color: "rose",
    icon: "shift",
    mission: "Primer registro del turno",
    introTitle: "Entra directo al turno",
    introGreeting: "Hola, {nombre}. Haz una acción útil sin buscar módulos.",
    introBody:
      "Verás solo acciones habilitadas para tu rol.",
    introSupport:
      "Si ya hiciste algo fuera de la guía, márcalo como hecho.",
    introCta: "Ver acciones",
    introSkip: "Cerrar por ahora",
    activeLabel: "Guía activa",
    completedBadge: "Turno iniciado",
    completionTitle: "Listo: ya completaste tu primera acción.",
    completionBody: "Continúa con el turno actual y registra lo necesario.",
    completionCta: "Ir al turno actual",
    completionRoute: "/dashboard",
    steps: [
      {
        id: "staff_review_beds",
        title: "Revisa camas",
        body: "Confirma disponibilidad antes de mover o asignar residentes.",
        help: "Si no hay cambios de cama hoy, puedes marcar este paso como hecho.",
        cta: "Revisar camas",
        route: "/camas",
        matchRoutes: ["/camas"],
        icon: "beds",
        requiredFeature: "beds",
        requiredPermission: "asignar_camas",
        manual: true,
      },
      {
        id: "staff_record_vital",
        title: "Registra un signo vital",
        body: "Guarda un control con validación de rangos clínicos.",
        help: "El sistema te avisará si un valor queda fuera del rango esperado.",
        cta: "Registrar signo",
        route: "/vital-signs/new",
        matchRoutes: ["/vital-signs"],
        icon: "vitals",
        requiredFeature: "vital-signs",
        requiredPermission: "crear_signos_vitales",
        manual: true,
      },
      {
        id: "staff_record_observation",
        title: "Escribe una observación",
        body: "Deja una novedad relevante para el siguiente turno.",
        help: "Escribe solo lo clínicamente útil para el siguiente turno.",
        cta: "Escribir observación",
        route: "/observations/new",
        matchRoutes: ["/observations"],
        icon: "observations",
        requiredFeature: "observations",
        requiredPermission: "crear_observaciones",
        manual: true,
      },
    ],
  },

  familiar: {
    id: "family_first_visit",
    role: "familiar",
    color: "sky",
    icon: "familiar",
    mission: "Primer contacto familiar",
    introTitle: "Conoce el portal familiar",
    introGreeting: "Hola, {nombre}. Revisa lo principal en pocos pasos.",
    introBody:
      "Parte por el resumen visible y registra una visita cuando corresponda.",
    introSupport: "Solo verás información habilitada para familiares.",
    introCta: "Comenzar",
    introSkip: "Cerrar por ahora",
    activeLabel: "Guía activa",
    completedBadge: "Portal iniciado",
    completionTitle: "Listo: ya conoces el portal familiar.",
    completionBody: "Desde aquí puedes revisar novedades y gestionar visitas.",
    completionCta: "Ver portal familiar",
    completionRoute: "/familiar",
    steps: [
      {
        id: "family_review_status",
        title: "Revisa el estado de tu familiar",
        body: "Consulta el resumen disponible del día.",
        help: "La información visible depende de lo que el ELEAM comparta con familiares.",
        cta: "Ver estado",
        route: "/familiar",
        matchRoutes: ["/familiar"],
        icon: "familiar",
        requiredFeature: "familiar",
        manual: true,
      },
      {
        id: "family_record_visit",
        title: "Registra una visita",
        body: "Guarda la visita con duración y una nota breve si aplica.",
        help: "Si la visita requiere validación, el equipo del ELEAM la revisará.",
        cta: "Registrar visita",
        route: "/familiar/visitas",
        matchRoutes: ["/familiar/visitas"],
        icon: "visits",
        requiredFeature: "familiar-visitas",
        manual: true,
      },
    ],
  },

  superadmin: {
    id: "platform_first_review",
    role: "superadmin",
    color: "slate",
    icon: "overview",
    mission: "Gestión inicial de plataforma",
    introTitle: "Gestiona lo urgente primero",
    introGreeting: "Hola, {nombre}. Revisa solicitudes y clientes sin rodeos.",
    introBody:
      "La guía prioriza acciones operativas, no métricas decorativas.",
    introSupport: "No agrega métricas ni tableros nuevos.",
    introCta: "Ver guía",
    introSkip: "Cerrar por ahora",
    activeLabel: "Guía activa",
    completedBadge: "Plataforma lista",
    completionTitle: "Listo: ya puedes continuar gestionando plataforma.",
    completionBody: "Mantén el flujo comercial y operativo desde superadmin.",
    completionCta: "Continuar",
    completionRoute: "/superadmin",
    steps: [
      {
        id: "platform_review_leads",
        title: "Revisa solicitudes",
        body: "Abre las solicitudes pendientes y decide el siguiente paso.",
        help: "Prioriza solicitudes con datos completos de ELEAM y contacto.",
        cta: "Ver solicitudes",
        route: "/superadmin/leads",
        matchRoutes: ["/superadmin/leads"],
        icon: "leads",
        manual: true,
      },
      {
        id: "platform_open_client",
        title: "Abre un cliente",
        body: "Revisa la ficha operativa antes de cualquier gestión.",
        help: "Usa la vista del cliente para validar estado, plan y notas internas.",
        cta: "Ver clientes",
        route: "/superadmin/clientes",
        matchRoutes: ["/superadmin/clientes"],
        icon: "clients",
        manual: true,
      },
      {
        id: "platform_continue",
        title: "Continúa gestionando plataforma",
        body: "Vuelve al panel superadmin cuando termines la revisión.",
        help: "Este paso solo cierra la activación inicial.",
        cta: "Continuar",
        route: "/superadmin",
        matchRoutes: ["/superadmin"],
        icon: "overview",
        manual: true,
      },
    ],
  },
};

export const ADMIN_FALLBACK_PLAYBOOK = {
  id: "admin_first_resident",
  role: "admin_eleam",
  color: "teal",
  icon: "residents",
  mission: "Primer residente registrado",
  introTitle: "Crea la primera ficha",
  introGreeting: "Hola, {nombre}. Parte con el primer residente.",
  introBody: "Registra solo los datos esenciales. Lo clínico puede completarse después.",
  introSupport: "Cuando Camas esté habilitado, podrás asignar ubicación.",
  introCta: "Comenzar",
  introSkip: "Cerrar por ahora",
  activeLabel: "Guía activa",
  completedBadge: "Ficha iniciada",
  completionTitle: "Listo: ya tienes el primer residente registrado.",
  completionBody: "Continúa con signos vitales, equipo o carpeta SEREMI.",
  completionCta: "Ver residentes",
  completionRoute: "/residents",
  steps: [
    {
      id: "resident_ready",
      title: "Registra un residente",
      body: "Completa solo los datos esenciales para crear su ficha.",
      help: "Puedes ampliar datos clínicos más adelante.",
      cta: "Registrar residente",
      route: "/residents/new",
      matchRoutes: ["/residents"],
      icon: "residents",
      requiredFeature: "residents",
      requiredPermission: "crear_residentes",
      completionRule: "hasActiveResident",
    },
  ],
};

export const COLOR_CLASSES = {
  teal: {
    bg: "bg-teal-50",
    bgSoft: "bg-teal-100",
    bgStrong: "bg-teal-600",
    text: "text-teal-700",
    textStrong: "text-teal-950",
    border: "border-teal-200",
    ring: "ring-teal-500",
    btn: "bg-teal-600 hover:bg-teal-700 focus:ring-teal-500 text-white",
    ghost: "text-teal-700 hover:bg-teal-50",
    progressColor: "#0d9488",
  },
  rose: {
    bg: "bg-rose-50",
    bgSoft: "bg-rose-100",
    bgStrong: "bg-rose-600",
    text: "text-rose-700",
    textStrong: "text-rose-950",
    border: "border-rose-200",
    ring: "ring-rose-500",
    btn: "bg-rose-600 hover:bg-rose-700 focus:ring-rose-500 text-white",
    ghost: "text-rose-700 hover:bg-rose-50",
    progressColor: "#e11d48",
  },
  sky: {
    bg: "bg-sky-50",
    bgSoft: "bg-sky-100",
    bgStrong: "bg-sky-600",
    text: "text-sky-700",
    textStrong: "text-sky-950",
    border: "border-sky-200",
    ring: "ring-sky-500",
    btn: "bg-sky-600 hover:bg-sky-700 focus:ring-sky-500 text-white",
    ghost: "text-sky-700 hover:bg-sky-50",
    progressColor: "#0284c7",
  },
  slate: {
    bg: "bg-slate-100",
    bgSoft: "bg-slate-200",
    bgStrong: "bg-slate-700",
    text: "text-slate-700",
    textStrong: "text-slate-950",
    border: "border-slate-300",
    ring: "ring-slate-500",
    btn: "bg-slate-700 hover:bg-slate-800 focus:ring-slate-500 text-white",
    ghost: "text-slate-700 hover:bg-slate-100",
    progressColor: "#475569",
  },
};
