export const DECRETO20_META = {
  normaCodigo: "DS20",
  nombre: "Decreto Supremo N°20 MINSAL",
  nombreCorto: "Decreto N°20",
  titulo:
    "Reglamento de Establecimientos de Larga Estadía para Personas Mayores (ELEAM)",
  fuenteUrl: "https://www.bcn.cl/leychile/navegar?idNorma=1182129",
  fuenteNombre: "Ley Chile / Biblioteca del Congreso Nacional de Chile",
  vigenciaDesde: "2025-10-01",
  modificacionesConsideradas: ["Decreto N°6/2025", "Decreto N°9/2025"],
  plazoGeneralAnios: 3,
  plazoIncendioAnios: 5,
  transitorios: [
    {
      plazo: "3 años desde la entrada en vigencia",
      descripcion:
        "Adecuación general para establecimientos en funcionamiento, con matriz de brechas y plan de cierre.",
    },
    {
      plazo: "5 años desde la entrada en vigencia",
      descripcion:
        "Adecuación específica de seguridad y protección contra incendios, con evidencia técnica y seguimiento.",
    },
  ],
  decretoDerogado: "normativa anterior",
  versionContenido: "2026-06-10",
};

export const DECRETO20_COPY = {
  hero:
    "Organiza la Carpeta SEREMI que exige el Decreto N°20 del MINSAL: matriz por artículos, evidencia documental con vencimientos, registros operativos vivos y modo fiscalización. FichaEleam está diseñado para apoyar la preparación documental de tu ELEAM ante la SEREMI; la validación final depende de la autoridad sanitaria.",
  propuesta:
    "Plataforma de gestión clínica, administrativa y documental para ELEAM, diseñada para apoyar el cumplimiento del Decreto N°20 MINSAL y sus modificaciones vigentes.",
  propuestaSegura:
    "Diseñado para apoyar la gestión y evidencia documental exigida por el Decreto N°20.",
  landing:
    "Digitaliza tu ELEAM y mantén ordenada la evidencia que exige el Decreto N°20.",
  seoDescription:
    "FichaEleam digitaliza la gestión clínica, administrativa y documental de ELEAM en Chile: carpeta SEREMI Decreto N°20, programa de atención integral, medicamentos, turnos y registros.",
};

export const DECRETO20_AMBITOS = [
  {
    codigo: "DS20-A05",
    nombre: "Autorización sanitaria",
    descripcion:
      "Antecedentes de solicitud, autorización de instalación y funcionamiento, documentos del establecimiento y programa integral.",
    icono: "📄",
    orden: 1,
    articulo_ref: "Art. 5",
  },
  {
    codigo: "DS20-A06",
    nombre: "Vigencia, observaciones y cierre",
    descripcion:
      "Resolución sanitaria, vigencia de tres años, observaciones SEREMI, subsanaciones y avisos de cierre.",
    icono: "🗓️",
    orden: 2,
    articulo_ref: "Art. 6",
  },
  {
    codigo: "DS20-A07",
    nombre: "Modificaciones ante SEREMI",
    descripcion:
      "Cambios de propietario, planta física, dirección técnica, personal, turnos o dotación.",
    icono: "🔁",
    orden: 3,
    articulo_ref: "Art. 7",
  },
  {
    codigo: "DS20-A08",
    nombre: "Infraestructura y ubicación",
    descripcion:
      "Condiciones sanitarias, accesibilidad, aseo, ubicación segura y evidencia física del establecimiento.",
    icono: "🏠",
    orden: 4,
    articulo_ref: "Arts. 8-9",
  },
  {
    codigo: "DS20-A10",
    nombre: "Instalaciones, equipamiento y seguridad",
    descripcion:
      "Letrero, habitaciones, baños, evacuación, incendios, cocina, sala de salud, medicamentos, lavandería y residuos.",
    icono: "🧯",
    orden: 5,
    articulo_ref: "Art. 10",
  },
  {
    codigo: "DS20-A12",
    nombre: "Dirección técnica y administrativa",
    descripcion:
      "Director técnico, director administrativo, jornada, reemplazo, validaciones y responsabilidades sanitarias.",
    icono: "🩺",
    orden: 6,
    articulo_ref: "Arts. 11-13",
  },
  {
    codigo: "DS20-A15",
    nombre: "Personal, competencias y dotación",
    descripcion:
      "Personal competente, técnicos, cuidadores, manipuladores, aseo, capacitaciones y cálculo de dotación por dependencia.",
    icono: "👥",
    orden: 7,
    articulo_ref: "Arts. 14-21",
  },
  {
    codigo: "DS20-A23",
    nombre: "Ingreso y carpeta personal",
    descripcion:
      "Consentimiento voluntario, condición de salud grave, historial social y de salud, evaluaciones y documentos del residente.",
    icono: "🧓",
    orden: 8,
    articulo_ref: "Arts. 22-24",
  },
  {
    codigo: "DS20-A25",
    nombre: "Protocolos y programa integral",
    descripcion:
      "Protocolos obligatorios, plan de capacitación anual, programa de atención integral usuaria e integración sociocomunitaria.",
    icono: "📋",
    orden: 9,
    articulo_ref: "Art. 25",
  },
  {
    codigo: "DS20-A26",
    nombre: "Red de salud y derivaciones",
    descripcion:
      "Controles de salud, APS o red privada, derivaciones, servicios externos y acceso de funcionarios de salud.",
    icono: "🏥",
    orden: 10,
    articulo_ref: "Art. 26",
  },
  {
    codigo: "DS20-A27",
    nombre: "Reglamento, contrato y registros",
    descripcion:
      "Reglamento interno, contrato, inventario, derechos y deberes, reclamos y registros específicos.",
    icono: "📝",
    orden: 11,
    articulo_ref: "Arts. 27-30",
  },
  {
    codigo: "DS20-A31",
    nombre: "Fiscalización, SENAMA y transitorios",
    descripcion:
      "Modo fiscalización, pauta MINSAL, reporte SENAMA, brechas críticas y plazos transitorios.",
    icono: "🔍",
    orden: 12,
    articulo_ref: "Arts. 3, 31-32 y transitorios",
  },
];

const defaults = {
  norma_codigo: DECRETO20_META.normaCodigo,
  fuente_url: DECRETO20_META.fuenteUrl,
  permite_no_aplica: true,
  requiere_vencimiento: false,
  vigencia_dias_sugerida: null,
  criticidad: "media",
  tipo_evidencia: "documento",
  origen_evidencia: "documental",
  requisito_operacional: false,
  obligatorio: true,
};

function req(values) {
  return { ...defaults, ...values };
}

export const DECRETO20_REQUISITOS = [
  req({
    codigo: "DS20-A05-SOLICITUD-AUTORIZACION",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5",
    nombre: "Solicitud de autorización sanitaria completa",
    descripcion:
      "Individualización del solicitante, establecimiento, director técnico, personal, cupos, residentes por sexo/género y nivel de dependencia.",
    medio_verificador:
      "Formulario o expediente SEREMI con identificación del titular, establecimiento, director técnico, personal y cupos.",
    criticidad: "critica",
    orden: 1,
  }),
  req({
    codigo: "DS20-A05-INMUEBLE-DOMINIO",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra c",
    nombre: "Dominio o derecho de uso del inmueble",
    descripcion: "Documento que acredita dominio, arriendo, comodato u otro derecho de uso y goce.",
    medio_verificador: "Escritura, contrato, certificado de dominio vigente u otro documento legal.",
    orden: 2,
  }),
  req({
    codigo: "DS20-A05-PLANO-CROQUIS",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra d",
    nombre: "Plano o croquis a escala",
    descripcion:
      "Debe identificar áreas, dormitorios, distribución de camas e instalaciones sanitarias de la zona de alimentos.",
    medio_verificador: "Plano o croquis a escala del establecimiento.",
    orden: 3,
  }),
  req({
    codigo: "DS20-A05-RECEPCION-FINAL",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra e",
    nombre: "Certificado de recepción final",
    descripcion: "Certificado emitido por la Dirección de Obras Municipales correspondiente.",
    medio_verificador: "Certificado DOM de recepción final.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 1095,
    orden: 4,
  }),
  req({
    codigo: "DS20-A05-AGUA-ALCANTARILLADO",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra f",
    nombre: "Agua potable, alcantarillado o sistemas particulares autorizados",
    descripcion: "Certificación o autorización sanitaria de agua potable, alcantarillado o sistemas particulares.",
    medio_verificador: "Certificados de servicios sanitarios o autorización sanitaria vigente.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "alta",
    orden: 5,
  }),
  req({
    codigo: "DS20-A05-PREVENCION-INCENDIOS",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra g",
    nombre: "Certificación de prevención y protección contra incendios",
    descripcion: "Certificado de experto en prevención de riesgos o Bomberos según normativa vigente.",
    medio_verificador: "Informe de experto o certificado de Bomberos.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "critica",
    orden: 6,
  }),
  req({
    codigo: "DS20-A05-ELECTRICIDAD-GAS",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra h",
    nombre: "Instalaciones eléctricas y de gas certificadas",
    descripcion: "Certificación de condiciones emitida por instalador autorizado u organismo competente.",
    medio_verificador: "Certificados SEC o equivalentes vigentes.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 1095,
    criticidad: "alta",
    orden: 7,
  }),
  req({
    codigo: "DS20-A05-DIRECTOR-TECNICO-ANTECEDENTES",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra i",
    nombre: "Antecedentes del director técnico",
    descripcion: "Certificado de título, carta de aceptación y distribución de jornada.",
    medio_verificador: "Título, carta de aceptación, contrato o anexo de jornada.",
    criticidad: "critica",
    orden: 8,
  }),
  req({
    codigo: "DS20-A05-PLANTA-PERSONAL-TURNOS",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra j",
    nombre: "Planta de personal, jornadas y sistema de turnos",
    descripcion: "Nómina y distribución de jornada del personal que funcionará en el establecimiento.",
    medio_verificador: "Nómina, contratos/anexos y cuadratura de turnos.",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 9,
  }),
  req({
    codigo: "DS20-A05-DERECHOS-DEBERES",
    ambito_codigo: "DS20-A05",
    articulo_ref: "Art. 5 letra t",
    nombre: "Carta de derechos y deberes visible",
    descripcion: "Carta elaborada por SENAMA en colaboración con MINSAL, visible y de uso común.",
    medio_verificador: "Archivo vigente y evidencia de publicación visible.",
    orden: 10,
  }),
  req({
    codigo: "DS20-A06-RESOLUCION-SANITARIA",
    ambito_codigo: "DS20-A06",
    articulo_ref: "Art. 6",
    nombre: "Resolución sanitaria de instalación y funcionamiento",
    descripcion: "Autorización SEREMI con vigencia de tres años y renovación automática mientras no sea dejada sin efecto.",
    medio_verificador: "Resolución sanitaria con número, fecha de otorgamiento y vigencia calculada.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 1095,
    criticidad: "critica",
    orden: 1,
  }),
  req({
    codigo: "DS20-A06-OBSERVACIONES-SEREMI",
    ambito_codigo: "DS20-A06",
    articulo_ref: "Art. 6",
    nombre: "Observaciones SEREMI y subsanaciones dentro de plazo",
    descripcion: "Registro de observaciones, plazo de siete días y acciones de subsanación.",
    medio_verificador: "Acta u oficio SEREMI, plan de subsanación y evidencia de cierre.",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A06-CIERRE-TRANSITORIO-DEFINITIVO",
    ambito_codigo: "DS20-A06",
    articulo_ref: "Art. 6",
    nombre: "Aviso de cierre transitorio o definitivo",
    descripcion: "Cuando corresponda, el titular debe avisar a SEREMI para suspensión o término de autorización.",
    medio_verificador: "Comunicación formal enviada a SEREMI y respuesta si existe.",
    obligatorio: false,
    orden: 3,
  }),
  req({
    codigo: "DS20-A07-MODIFICACION-PROPIETARIO-PLANTA",
    ambito_codigo: "DS20-A07",
    articulo_ref: "Art. 7 letra a",
    nombre: "Solicitud por cambio de propietario o planta física",
    descripcion: "Debe presentarse dentro de 20 días hábiles desde el cambio.",
    medio_verificador: "Solicitud SEREMI, antecedentes de respaldo y resolución.",
    obligatorio: false,
    criticidad: "alta",
    orden: 1,
  }),
  req({
    codigo: "DS20-A07-CAMBIO-DIRECTOR-TECNICO",
    ambito_codigo: "DS20-A07",
    articulo_ref: "Art. 7 letra b",
    nombre: "Solicitud por cambio de director técnico",
    descripcion: "Debe presentarse dentro de 5 días hábiles desde el cambio.",
    medio_verificador: "Solicitud, título, carta de aceptación y jornada del nuevo director técnico.",
    obligatorio: false,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A07-CAMBIO-PERSONAL-TURNOS",
    ambito_codigo: "DS20-A07",
    articulo_ref: "Art. 7 letra c",
    nombre: "Solicitud por cambio de personal, jornada, turnos o dotación",
    descripcion: "Debe presentarse dentro de 5 días hábiles cuando afecta personal o proporción con residentes.",
    medio_verificador: "Solicitud SEREMI y nueva planta de personal con turnos.",
    obligatorio: false,
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 3,
  }),
  req({
    codigo: "DS20-A08-INFRAESTRUCTURA-SEGURA",
    ambito_codigo: "DS20-A08",
    articulo_ref: "Art. 8",
    nombre: "Infraestructura libre de riesgo estructural y sanitario",
    descripcion: "Muros, pisos, instalaciones sanitarias, iluminación, climatización y superficies en buen estado.",
    medio_verificador: "Checklist de infraestructura, fotografías y mantenciones.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 1,
  }),
  req({
    codigo: "DS20-A08-ASEO-DESINFECCION",
    ambito_codigo: "DS20-A08",
    articulo_ref: "Art. 8 letra g",
    nombre: "Rutina de aseo y desinfección",
    descripcion: "Procedimiento de aseo y limpieza con desinfectantes según protocolos MINSAL.",
    medio_verificador: "Procedimiento vigente y bitácoras de aseo.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    orden: 2,
  }),
  req({
    codigo: "DS20-A08-UBICACION-SEGURA",
    ambito_codigo: "DS20-A08",
    articulo_ref: "Art. 9",
    nombre: "Ubicación alejada de fuentes de riesgo sanitario",
    descripcion: "Al menos 500 metros de residuos, aguas residuales, ruidos, gases u otras emanaciones de riesgo.",
    medio_verificador: "Declaración, mapa, informe municipal o respaldo territorial.",
    criticidad: "alta",
    orden: 3,
  }),
  req({
    codigo: "DS20-A10-LETRERO-AUTORIZACION",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra a",
    nombre: "Letrero de autorización en frontis",
    descripcion: "Mínimo 40 x 40 cm, letras de al menos 2 cm, número y fecha de resolución sanitaria.",
    medio_verificador: "Fotografía del frontis y datos de resolución.",
    orden: 1,
  }),
  req({
    codigo: "DS20-A10-HABITACIONES-CAMAS",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra j",
    nombre: "Habitaciones y camas según estándar DS 20",
    descripcion: "Máximo 4 camas por habitación, circulación mínima, guardado individual, mesa de noche y sistema de llamado.",
    medio_verificador: "Plano/croquis, registro de habitaciones/camas y checklist de equipamiento.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A10-EVACUACION-INCENDIOS",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letras k-m",
    nombre: "Seguridad contra incendios y vías de evacuación",
    descripcion: "Cumplimiento de normativa de incendios, salidas expeditas, iluminación autónoma, señalética y plano de evacuación.",
    medio_verificador: "Certificados, plan de evacuación, señalética y evidencia fotográfica.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "critica",
    orden: 3,
  }),
  req({
    codigo: "DS20-A10-BANOS-ACCESIBLES",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra n",
    nombre: "Servicios higiénicos accesibles y suficientes",
    descripcion: "Al menos 1 baño por cada 5 residentes, con ducha teléfono, barras, alerta, agua fría/caliente y baño asistido.",
    medio_verificador: "Checklist por baño, fotografías y relación baños/residentes.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    criticidad: "alta",
    orden: 4,
  }),
  req({
    codigo: "DS20-A10-COCINA-ALIMENTOS",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra o",
    nombre: "Cocina o zona de alimentos autorizada",
    descripcion: "Debe cumplir DS N°977/1996 y estar incorporada en autorización del establecimiento.",
    medio_verificador: "Autorización sanitaria, checklist de cocina y certificados de manipuladores.",
    criticidad: "alta",
    orden: 5,
  }),
  req({
    codigo: "DS20-A10-SALA-SALUD-EQUIPO-MOVIL",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra p",
    nombre: "Sala de salud o equipo móvil con insumos mínimos",
    descripcion: "Esfigmomanómetro, fonendoscopio, termómetro, glicemia, saturómetro, primeros auxilios y estantería de carpetas.",
    medio_verificador: "Inventario de equipamiento, fotografías y revisión periódica.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    criticidad: "alta",
    orden: 6,
  }),
  req({
    codigo: "DS20-A10-MEDICAMENTOS-ALMACENAMIENTO",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letra q",
    nombre: "Almacenamiento seguro de medicamentos",
    descripcion: "Acceso restringido, temperatura menor a 25 °C, gavetas individualizadas, cadena de frío y controlados bajo llave.",
    medio_verificador: "Registro de almacenamiento, temperatura, gavetas, lote, vencimiento y responsable.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 7,
  }),
  req({
    codigo: "DS20-A10-LAVANDERIA-RESIDUOS",
    ambito_codigo: "DS20-A10",
    articulo_ref: "Art. 10 letras r-t",
    nombre: "Aseo, lavandería y residuos domiciliarios",
    descripcion: "Espacios e insumos para aseo, flujo de ropa sucia/limpia y retiro de residuos al menos diario o al 3/4 de capacidad.",
    medio_verificador: "Procedimientos, bitácoras y evidencia de espacios diferenciados.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    orden: 8,
  }),
  req({
    codigo: "DS20-A12-DIRECTOR-CALIFICACION",
    ambito_codigo: "DS20-A12",
    articulo_ref: "Art. 12",
    nombre: "Director técnico con calificación exigida",
    descripcion: "Título profesional salud/social de 8 o más semestres, habilitación y postítulo/experiencia en geriatría, gerontología o ELEAM.",
    medio_verificador: "Título, habilitación, diplomado/postítulo o certificado de experiencia.",
    criticidad: "critica",
    orden: 1,
  }),
  req({
    codigo: "DS20-A12-JORNADA-REEMPLAZO",
    ambito_codigo: "DS20-A12",
    articulo_ref: "Art. 13",
    nombre: "Permanencia, reemplazante y disponibilidad del director técnico",
    descripcion: "4 horas semanales hasta 15 residentes, 5 horas si mayor capacidad, reemplazante y disponibilidad telefónica.",
    medio_verificador: "Contrato/anexo de jornada, registro de asistencia, reemplazante designado.",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A12-VALIDACIONES-DIRECCION-TECNICA",
    ambito_codigo: "DS20-A12",
    articulo_ref: "Art. 12",
    nombre: "Validaciones clínicas y sociales por dirección técnica",
    descripcion: "Dependencia funcional, cognitiva y nutricional al ingreso, programa integral, red de salud, medicamentos y eventos críticos.",
    medio_verificador: "Registros firmados/validados, evaluaciones y reportes de seguimiento.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 3,
  }),
  req({
    codigo: "DS20-A12-REPORTE-SENAMA",
    ambito_codigo: "DS20-A12",
    articulo_ref: "Art. 12 N°24",
    nombre: "Reporte trimestral a SENAMA",
    descripcion: "Información administrativa, residentes y trabajadores reportada al menos trimestralmente.",
    medio_verificador: "Reporte trimestral SENAMA, PDF/Excel/CSV y comprobante de envío.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 90,
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 4,
  }),
  req({
    codigo: "DS20-A15-CALCULADORA-DOTACION-DEPENDENCIA",
    ambito_codigo: "DS20-A15",
    articulo_ref: "Arts. 15-17",
    nombre: "Dotación calculada por dependencia y turno",
    descripcion: "Cuidadores diurnos/nocturnos según dependencia, autovalencia y mínimo nocturno de dos cuidadores.",
    medio_verificador: "Cálculo de dotación, nómina por turno y residentes por dependencia.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 1,
  }),
  req({
    codigo: "DS20-A15-TENS-AUXILIAR",
    ambito_codigo: "DS20-A15",
    articulo_ref: "Art. 18",
    nombre: "Auxiliar o técnico de enfermería disponible según norma",
    descripcion: "12 horas diurnas y llamada nocturna para residentes con dependencia; llamada 24 horas para autovalentes.",
    medio_verificador: "Turnos, contratos, certificados y registros de llamada.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A15-COMPETENCIAS-CUIDADORES",
    ambito_codigo: "DS20-A15",
    articulo_ref: "Arts. 18-19",
    nombre: "Competencias y capacitaciones de cuidadores/TENS",
    descripcion: "Medicamentos, signos vitales, alimentación por sonda, insulina/heparina, soporte vital básico y actividades de vida diaria.",
    medio_verificador: "Certificados, plan de capacitación anual y matriz de competencias.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 3,
  }),
  req({
    codigo: "DS20-A15-MANIPULADORES-ALIMENTOS",
    ambito_codigo: "DS20-A15",
    articulo_ref: "Art. 20",
    nombre: "Manipuladores de alimentos o servicio externalizado",
    descripcion: "Personal o servicio que cumple DS N°977/1996, con plan de contingencia si corresponde.",
    medio_verificador: "Nómina, certificados, contrato de servicio externo y plan de contingencia.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    orden: 4,
  }),
  req({
    codigo: "DS20-A23-CONSENTIMIENTO-INGRESO",
    ambito_codigo: "DS20-A23",
    articulo_ref: "Art. 23",
    nombre: "Consentimiento voluntario de ingreso",
    descripcion: "La voluntad libre y expresa debe constar por escrito; puede firmar representante legal si corresponde.",
    medio_verificador: "Consentimiento firmado y registro de representante legal cuando aplique.",
    criticidad: "critica",
    orden: 1,
  }),
  req({
    codigo: "DS20-A23-CONDICION-SALUD-GRAVE",
    ambito_codigo: "DS20-A23",
    articulo_ref: "Art. 23",
    nombre: "Evaluación de condición de salud grave al ingreso",
    descripcion: "No pueden ingresar personas con condición que requiera asistencia médica continua o permanente.",
    medio_verificador: "Declaración/evaluación de ingreso, informe de salud y validación técnica.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 2,
  }),
  req({
    codigo: "DS20-A23-EVALUACIONES-GERIATRICAS",
    ambito_codigo: "DS20-A23",
    articulo_ref: "Arts. 12 y 23",
    nombre: "Evaluaciones funcional, cognitiva y nutricional",
    descripcion: "Determinación del nivel de dependencia mediante instrumentos de valoración geriátrica integral.",
    medio_verificador: "Evaluaciones registradas, puntajes, instrumentos usados y fecha de próxima evaluación.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 3,
  }),
  req({
    codigo: "DS20-A23-CARPETA-PERSONAL-ACTUALIZADA",
    ambito_codigo: "DS20-A23",
    articulo_ref: "Art. 29",
    nombre: "Carpeta personal digital actualizada",
    descripcion: "Sistema de salud, historial de salud, historial social, medicamentos, registros diarios y acceso restringido.",
    medio_verificador: "Carpeta digital por residente con auditoría, documentos y registros recientes.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 4,
  }),
  req({
    codigo: "DS20-A24-EVENTOS-AGUDOS-DERIVACION",
    ambito_codigo: "DS20-A23",
    articulo_ref: "Art. 24",
    nombre: "Registro de eventos agudos, indicación médica y derivación",
    descripcion: "Continuidad excepcional con indicación médica escrita o traslado a establecimiento resolutivo/urgencia.",
    medio_verificador: "Evento crítico, signos vitales, indicación médica, consentimiento informado y derivación.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 5,
  }),
  req({
    codigo: "DS20-A25-PROTOCOLO-INGRESO-EGRESO",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°1",
    nombre: "Protocolo de ingreso y egreso",
    descripcion: "Incluye dependencia, evaluación de ingreso, consentimiento, inducción y situaciones de egreso.",
    medio_verificador: "Protocolo vigente, versión, responsable y evidencia de aplicación.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    orden: 1,
  }),
  req({
    codigo: "DS20-A25-CAPACITACION-ANUAL-22H",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°2",
    nombre: "Plan de inducción y capacitación anual de 22 horas",
    descripcion: "Objetivos, contenidos, evaluación y duración mínima de 22 horas.",
    medio_verificador: "Plan anual, asistencia, evaluaciones y certificados emitidos.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A25-PLAN-EMERGENCIAS",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°3",
    nombre: "Plan de emergencias y desastres",
    descripcion: "Incendios, sismos, cortes de agua/luz, robos y otros eventos, con responsables y herramientas.",
    medio_verificador: "Plan vigente, simulacros, responsables y evidencias de socialización.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "critica",
    orden: 3,
  }),
  req({
    codigo: "DS20-A25-URGENCIAS-FALLECIMIENTO",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°4-5",
    nombre: "Protocolos de urgencias médicas y fallecimiento",
    descripcion: "Protocolos actualizados, socializados y aplicables por el equipo.",
    medio_verificador: "Protocolos, versiones, responsables y evidencia de capacitación.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "alta",
    orden: 4,
  }),
  req({
    codigo: "DS20-A25-PROGRAMA-INTEGRAL-USUARIA",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°6",
    nombre: "Programa de atención integral usuaria vigente",
    descripcion: "Intervenciones biopsicosociales de prevención, mantención, promoción, necesidades básicas, autonomía y bienestar.",
    medio_verificador: "Programa individual vigente, intervenciones, frecuencia, responsable y validación técnica.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 5,
  }),
  req({
    codigo: "DS20-A25-INTEGRACION-SOCIOCOMUNITARIA",
    ambito_codigo: "DS20-A25",
    articulo_ref: "Art. 25 N°7",
    nombre: "Plan de integración sociocomunitaria",
    descripcion: "Redes socioafectivas, persona significativa, inclusión comunitaria, voluntariado y actividades intergeneracionales.",
    medio_verificador: "Plan, actividades, participantes, calendario y registros de ejecución.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    orden: 6,
  }),
  req({
    codigo: "DS20-A26-RED-SALUD-APS-PRIVADA",
    ambito_codigo: "DS20-A26",
    articulo_ref: "Art. 26",
    nombre: "Vinculación con red de salud",
    descripcion: "Control de salud mediante APS o centro privado y acceso de funcionarios de salud al ELEAM.",
    medio_verificador: "Centro de salud por residente, controles, derivaciones y contactos de red.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 1,
  }),
  req({
    codigo: "DS20-A26-SERVICIOS-PRIVADOS",
    ambito_codigo: "DS20-A26",
    articulo_ref: "Art. 26",
    nombre: "Servicios privados cuando no hay acceso oportuno",
    descripcion: "Preferentemente geriatra, neurólogo o médico de familia cuando corresponda.",
    medio_verificador: "Contratos, órdenes, informes y registros de atención.",
    obligatorio: false,
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    orden: 2,
  }),
  req({
    codigo: "DS20-A27-REGLAMENTO-INTERNO",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 27",
    nombre: "Reglamento interno visible, entregado y explicado",
    descripcion: "Debe declarar derechos, autonomía, reclamos, uso de lugares comunes, orden, higiene y seguridad.",
    medio_verificador: "Reglamento vigente, evidencia visible, entrega y explicación al ingreso.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    criticidad: "alta",
    orden: 1,
  }),
  req({
    codigo: "DS20-A28-CONTRATO-RESIDENCIA",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 28",
    nombre: "Contrato de residencia sin cláusulas prohibidas",
    descripcion: "Derechos/deberes, causales de exclusión, rendición de gastos si aplica e inventario.",
    medio_verificador: "Contrato firmado por residente o representante y revisión documental.",
    criticidad: "critica",
    orden: 2,
  }),
  req({
    codigo: "DS20-A28-INVENTARIO-BIENES",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 28",
    nombre: "Inventario de bienes al ingreso, anual y egreso",
    descripcion: "Inventario simple de bienes personales al ingreso, al menos anual y al término del contrato.",
    medio_verificador: "Inventario firmado, revisión anual y registro de egreso.",
    requiere_vencimiento: true,
    vigencia_dias_sugerida: 365,
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    orden: 3,
  }),
  req({
    codigo: "DS20-A29-REGISTRO-RECLAMOS",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 29 N°2",
    nombre: "Registro de sugerencias o reclamos visible y codificado",
    descripcion: "Libro foliado o digitalizado, con codificación y fácil consulta para residentes, familiares o persona significativa.",
    medio_verificador: "Registro digital/foliado, códigos, estados, respuestas y cierres.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 4,
  }),
  req({
    codigo: "DS20-A29-DERECHOS-ENTREGADOS",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 29 N°4",
    nombre: "Carta de derechos y deberes entregada al ingreso",
    descripcion: "Entrega por escrito al ingreso y consignación en consentimiento.",
    medio_verificador: "Registro de entrega, firma o confirmación digital.",
    criticidad: "alta",
    orden: 5,
  }),
  req({
    codigo: "DS20-A30-DATOS-SENSIBLES",
    ambito_codigo: "DS20-A27",
    articulo_ref: "Art. 30",
    nombre: "Reserva y control de datos personales sensibles",
    descripcion: "El personal con acceso a datos sensibles debe guardar reserva conforme a Ley N°19.628 y normativa aplicable.",
    medio_verificador: "Roles, permisos, auditoría de acceso y compromisos de confidencialidad.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    criticidad: "critica",
    orden: 6,
  }),
  req({
    codigo: "DS20-A31-MODO-FISCALIZACION",
    ambito_codigo: "DS20-A31",
    articulo_ref: "Art. 31",
    nombre: "Modo fiscalización SEREMI con evidencia descargable",
    descripcion: "SEREMI fiscaliza cumplimiento del reglamento y MINSAL proporciona pauta de fiscalización publicada y actualizada.",
    medio_verificador: "Carpeta exportable, matriz de brechas, documentos y registros por artículo.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 1,
  }),
  req({
    codigo: "DS20-A31-PLAZOS-TRANSITORIOS",
    ambito_codigo: "DS20-A31",
    articulo_ref: "Art. 1 transitorio",
    nombre: "Control de plazos transitorios DS 20",
    descripcion: "Obligación general cumplidos 3 años desde vigencia y 5 años para seguridad contra incendios.",
    medio_verificador: "Matriz de cumplimiento transitorio y plan de adecuación.",
    tipo_evidencia: "registro",
    origen_evidencia: "mixta",
    requisito_operacional: true,
    criticidad: "alta",
    orden: 2,
  }),
  req({
    codigo: "DS20-A31-REPORTES-SENAMA-SEREMI",
    ambito_codigo: "DS20-A31",
    articulo_ref: "Arts. 3 y 31",
    nombre: "Reportes y antecedentes para SENAMA/SEREMI",
    descripcion: "Capacidad de conservar y generar información administrativa, residentes, trabajadores, brechas y subsanaciones.",
    medio_verificador: "Reportes PDF/Excel/CSV, historial de envíos y respaldo de comunicaciones.",
    tipo_evidencia: "registro",
    origen_evidencia: "operacional",
    requisito_operacional: true,
    orden: 3,
  }),
];

export const DECRETO20_FAQ = [
  {
    q: "¿Qué cambió con el Decreto N°20 para los ELEAM?",
    a: "El Decreto N°20 actualiza el reglamento de ELEAM, refuerza el enfoque de derechos, autonomía, programa de atención integral usuaria, registros, protocolos, dotación, fiscalización y evidencia operativa.",
  },
  {
    q: "¿Desde cuándo está vigente el Decreto N°20?",
    a: "La versión consolidada revisada indica entrada en vigencia desde el 1 de octubre de 2025, con disposiciones transitorias para ELEAM en funcionamiento.",
  },
  {
    q: "¿Qué pasa con la normativa anterior?",
    a: "El documento normativo de trabajo indica que la normativa anterior queda reemplazada una vez que entra en vigencia el Decreto N°20.",
  },
  {
    q: "¿FichaEleam garantiza cumplimiento automático?",
    a: "No. FichaEleam está diseñado para apoyar la gestión y evidencia documental exigida por el Decreto N°20. La validación final depende del texto oficial vigente, pauta MINSAL, criterio SEREMI y asesoría sanitaria cuando corresponda.",
  },
];

export const PUBLIC_ROUTES = [
  { path: "/", priority: "1.00", changefreq: "weekly" },
  { path: "/software-eleam", priority: "0.95", changefreq: "monthly" },
  { path: "/acreditacion-seremi", priority: "0.95", changefreq: "monthly" },
  { path: "/calculadora-dotacion-eleam", priority: "0.90", changefreq: "monthly" },
  { path: "/autoevaluacion-decreto-20", priority: "0.90", changefreq: "monthly" },
  { path: "/plazos-decreto-20", priority: "0.90", changefreq: "monthly" },
  { path: "/preguntas-frecuentes", priority: "0.70", changefreq: "monthly" },
  { path: "/contacto", priority: "0.70", changefreq: "monthly" },
  { path: "/pago", priority: "0.75", changefreq: "monthly" },
  { path: "/blog", priority: "0.90", changefreq: "weekly" },
];

export const PRIVATE_NOINDEX_ROUTES = [
  "/login",
  "/register",
  "/recuperar-acceso",
  "/reset-password",
  "/cambiar-clave",
  "/dashboard",
  "/operacion/turnos",
  "/residents",
  "/establecimiento/camas",
  "/vital-signs",
  "/observations",
  "/eventos-adversos",
  "/cumplimiento/seremi",
  "/personal/equipo",
  "/superadmin",
];
